"""create_db

Revision ID: 23cec2f64b2f
Revises: 
Create Date: 2024-04-22 22:09:30.920739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23cec2f64b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('physical_server',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('importance', sa.Enum('HIGH', 'COMMON', 'LOW', name='importance'), nullable=False),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_warranty_data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('vendor_email', sa.String(), nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_server_id'), 'physical_server', ['id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_physical_server_id'), table_name='physical_server')
    op.drop_table('physical_server')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
